# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafui < Formula
  desc "Terminal ui inspired by k9s to quickly browse multiple kafka instances"
  homepage "https://github.com/Benny93/kafui"
  version "0.1.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.23/kafui_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "f004ebc6bc8f5050bca7ba1b9f37fe9ecea4d42f161b20349f2ba48297d0bee2"

      def install
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.23/kafui_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7deffd1c0187fb378c95fb7a73e760af2e3f9e650e4c3e3591cfdeb116f1fbb3"

      def install
        bin.install "kafui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.23/kafui_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "94d98480813ee366547f722d2d1b98be3466075c38983ceead8945aaf6e477eb"

      def install
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.23/kafui_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "c0f63f3907542c23265a77548542bb4d49e8ef945719c59c79e3ed596cafc5f2"

      def install
        bin.install "kafui"
      end
    end
  end

  def caveats
    <<~EOS
      Run using kafui
    EOS
  end
end
