# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafui < Formula
  desc "Terminal ui inspired by k9s to quickly browse multiple kafka instances"
  homepage "https://github.com/Benny93/kafui"
  version "0.1.32"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Benny93/kafui/releases/download/0.1.32/kafui_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d0f960f838ad4bad7f4603bbd6259113fe43d06a0f8a2e0eb88ecbe14250c596"

      def install
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Benny93/kafui/releases/download/0.1.32/kafui_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5e49a54be9fd90bad47b88745de879b54b7f478e31fd53deb8c1e5b89fee0a24"

      def install
        bin.install "kafui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Benny93/kafui/releases/download/0.1.32/kafui_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "66b6cae1d635a375b9ec34ca6248f673381458b98f4d712c79b803445a562d2a"
      def install
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Benny93/kafui/releases/download/0.1.32/kafui_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d1a427e4af3ec59684320da6a68a53e9cc5ea48c9e736fc99d80fcaa3f001dfc"
      def install
        bin.install "kafui"
      end
    end
  end

  def caveats
    <<~EOS
      Run using kafui
    EOS
  end
end
