# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kafui < Formula
  desc "Terminal ui inspired by k9s to quickly browse multiple kafka instances"
  homepage "https://github.com/Benny93/kafui"
  version "0.1.36"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.36/kafui_darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "5b9773a185a42965a0bf60af023c688fd7e46dfab97fe0a8aede0a4e7f0685b5"

      define_method(:install) do
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.36/kafui_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "5311aef799b32bd29500276752824daab947c72b1b30f3d4d3594024f4ecb6f6"

      define_method(:install) do
        bin.install "kafui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.36/kafui_linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6504001834b13ff39bf80c2c23f2b46f7b5c29e06175cdd878193e9bb9b4ef23"
      define_method(:install) do
        bin.install "kafui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Benny93/kafui/releases/download/v0.1.36/kafui_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f63b7a4cd5765df799e4b6c05ad8ace16cad4d8bd510f605526b52e9ac9bb3d4"
      define_method(:install) do
        bin.install "kafui"
      end
    end
  end

  def caveats
    <<~EOS
      Run using kafui
    EOS
  end
end
